### ISSUE TITLE
README improvement suggestion

### ISSUE THREAD

**Issue by Aju100** [manibibek/payment-gateways-in-nepal#1]
Hi @manibibek ,

As this repo is still a new one, I would like you to refer to the reference of the README template and its design from [tech companies in Nepal one.](https://github.com/mesaugat/tech-companies-in-nepal). This can help to improve your repo and it's documentation.

**Comment by manibibek** [comment]
Hi @Aju100, 

Thank you so much for your feedback. This is a work in progress and I'm still working on redesigning the template and adding proper contributing guidelines.  Suggestions and feedbacks regarding the same would be of great help, specially in its initial phase. 

I have taken reference from https://github.com/mesaugat/tech-companies-in-nepal and a few other similar repositories but this repository is aimed at collecting more nested information about any Payment Gateway than just listing it so need to come up with a different template. 

Please feel free to reply back or create issues if you have any feedback or questions. 

Thank you

**Comment by Aju100** [comment]
@manibibek I am delighted to receive your response to the improvement suggestion on README docs. If there are any things, I would love to take up a new issue for it. Thanks

**Comment by manibibek** [comment]
@Aju100 Feel free to add more development resources for any Payment Gateways listed or add unlisted Payment Gateways and it's resources. Thanks

**Comment by Aju100** [comment]
Hi @manibibek,

I think having a GitHub-pages with a Jekyll theme is much more appreciated for the enhancement feature.
Only the owner of this repository or forked repo (children repo) can able to created Github-page.

Impact: Developer can easily access with custom domain too.

Reference: [Creating a GitHub Pages site](https://docs.github.com/en/github/working-with-github-pages/creating-a-github-pages-site#:~:text=You%20can%20create%20a%20GitHub,Cloud%2C%20and%20GitHub%20Enterprise%20Server.)

Regards,
Aju Tamang
